ALTER TABLE "Setting" ADD COLUMN "category" TEXT NOT NULL DEFAULT 'advanced';
ALTER TABLE "Setting" ADD COLUMN "isSecret" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Setting" ADD COLUMN "updatedBy" TEXT;
